### ISSUE TITLE
Vimeowrap and Google Analytics

### ISSUE THREAD

**Issue by bobd72** [luwes/vimeowrap.js#12]
Hi,
Thanks for the excellent code which works really well.  I am having a problem tracking access to videos using Google analytics.  I keep getting the following error:

[Error] SyntaxError: DOM Exception 12: An invalid or illegal string was specified.
postMessage (vimeo.ga.min.js, line 8)
post (vimeo.ga.min.js, line 8)
(anonymous function) (vimeo.ga.min.js, line 8)
each (jquery.min.js, line 2)
onReady (vimeo.ga.min.js, line 8)
onMessageReceived (vimeo.ga.min.js, line 8)

Any thoughts?

Thanks

**Comment by luwes** [comment]
Sorry, can't immediately see what's going on by this log. Do you have a test page online?
