### ISSUE TITLE
Playlist show only 20 videos

### ISSUE THREAD

**Issue by maulik2582** [luwes/vimeowrap.js#13]
Playlist show only 20 videos while using plugins like Carousel OR Playlist.

I have added 30+ videos on my vimeo channel but it shows only 20 videos in playlist.

**Comment by luwes** [comment]
It's possible to add a second url with the `?page=2` parameter I believe. 
See here for more info https://developer.vimeo.com/api/endpoints/videos

**Comment by maulik2582** [comment]
Hi Wesley Luyten,

I really appreciate your help. This really ended my many days of R&D and frustration :).

I added same channel URL adding ?page=X for multiple times to render all videos of channel.

Is it still possible to render all the videos of channel without ?page=X ??

Also, One more non vimeowrap help is needed. Is it possible to make Channel password protected instead of individual videos? So it asks for password just once per channel.

**Comment by maulik2582** [comment]
Hi Wesley Luyten,

I really appreciate your help. This really ended my many days of R&D
and frustration :).

I added same channel URL adding ?page=X for multiple times to render all
videos of channel.

Is it still possible to render all the videos of channel without ?page=X ??

Also, One more non vimeowrap help is needed. Is it possible to make Channel
password protected instead of individual videos? So it asks for password
just once per channel.





On Fri, Nov 20, 2015 at 12:06 AM, wesley luyten <notifications@github.com>
wrote:

> It's possible to add a second url with the ?page=2 parameter I believe.
> See here for more info https://developer.vimeo.com/api/endpoints/videos
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luwes/vimeowrap.js/issues/13#issuecomment-158149772>.
>



-- 

*Thanks,*

*Maulik Mistry*

**Comment by luwes** [comment]
It's not possible out of the box, you would need to make your own server side request which would return all the videos. Your server side script would talk to the Vimeo API instead of vimeowrap.
