### ISSUE TITLE
Issues with Large Dynamic Albums or Collections

### ISSUE THREAD

**Issue by njfilmschool** [luwes/vimeowrap.js#14]
VimeoWrap is brilliant for small groups of videos.

But when you have large groups of videos, it won't dynamically load them all.  You need to add a new line for each page.  And you can only do that if you know the exact number of pages.  If your library grows, you then need to add new lines to your code.  If you try to add extra lines in the code (with unused pages numbers) to plan for growth, it breaks the system and nothing loads.

It would be awesome, if there was another way to load videos that didn't require specifying page numbers.

I'm not a great programmer, but I did a quick look here (https://developer.vimeo.com/api/endpoints/channels#/{channel_id}/videos) and it looks like you should be able to pass a channel number and get a list of ALL the videos in return (not just one page at a  time).

**Comment by luwes** [comment]
The best solution to this would to write your own server side script which would get all the videos through the Vimeo API and then return that as a response to vimeowrap.
