### ISSUE TITLE
Using Vimeo's Advanced API with vimeowrap?

### ISSUE THREAD

**Issue by brutus** [luwes/vimeowrap.js#15]
What is the status of this? Seems vimeowrap still uses the _Simple API_ only. If so, any plans on supporting the _Advanced API_ in the future? Or is that outside the scope?

And if you don't mind me asking, what are your suggestions for solving this right now? Is it relatively easy to patch vimeowrap.js so that it can also use the _Advanced API_ to fetch videos? Or should I better start from scratch with one of the [official libraries](https://developer.vimeo.com/api/libraries)?

**Comment by luwes** [comment]
Hi Brutus, it's not really a plan to support the advanced API because it would require server side processing. The best way would be indeed start from scratch and get the advanced api working and maybe then use parts of vimeowrap as you see fit. Hope this helps.
