### ISSUE TITLE
Playlist using channel not working

### ISSUE THREAD

**Issue by shile23** [luwes/vimeowrap.js#16]
Hi,

I tried using your playlist implementation with vimeo channel,and it is loading the videos but cant play them.Can this be fixed?

Here is the [jsfiddle](http://jsfiddle.net/uPgMv/1157/) of the issue.

**Comment by luwes** [comment]
Sorry, private videos are not supported. See here, https://github.com/luwes/vimeowrap.js/issues/1#issuecomment-5894185
