### ISSUE TITLE
change size (height) of playlist.

### ISSUE THREAD

**Issue by apricot1101** [luwes/vimeowrap.js#20]
Thank you for your js files !!!
I was looking for a playlist player of Vimeo, like just your source.
I have a question.
I want to change size (height) of playlist.

`<script>
    vimeowrap('player').setup({
        urls: [
            'https://vimeo.com/user3709818'
        ],
					width: 300,
					height: 169,
					repeat: 'list',
					title: false,
					byline: false,
					badge: false,
					portrait: false,
					color: '009900',
        plugins: {
            'playlist':{}
        }
    });
</script>`

I changed "height: 169" to "height: 400". However it was changed height of vimeo player, not playlist.
Is there a way to change size (height) of playlist ?

best regards

**Comment by luwes** [comment]
See here for more info on the playlist config, https://wesleyluyten.com/projects/vimeo-wrap/playlist
So something like this would do it `plugins: { 'playlist':{ size: 230 } }`

**Comment by apricot1101** [comment]
Thank you  for your prompt reply !!!
And I'm sorry I missed its page.
Best regards

**Comment by Talkinggod** [comment]
HI  
Thanks for you r scripting 
I have been trying to use it and make the player responsive
I was able to get embedded Vimeo I frames to be responsive so it will resize to mobile phones  with this CSS 
/* Youtube Reflexive */
.vid-container {
    position: relative;
    padding-bottom: 50%;
    padding-top: 35px; height: 0; overflow: hidden;
}

.vid-container iframe,
.vid-container object,
.vid-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
Next, edit add some HTML around your embed code.

HTML
<div class="vid-container">
         <iframe width="xxx" height="xxx" src="http://www.youtube.com/embed/(EMBED CODE)" frameborder="0"></iframe>
</div>
( https://www.webatude.com/how-to-make-youtube-videos-reflexive-and-mobile-friendly/)
I cannot get this to work with your Vimeo playlist ( but it works with youtube url's and Iframe embed codes) 
is there  something I am missing ?  Getting the play list to be responsive in a page layout is really useful

Thanks
