### ISSUE TITLE
Playlist: Video titles and descriptions are truncated 

### ISSUE THREAD

**Issue by alex-michel** [luwes/vimeowrap.js#23]
Is there a setting that will let me use a longer video title in a wider playlist viewport?

See screen cap:

![image](https://user-images.githubusercontent.com/35116459/34584734-f2cb0c68-f16a-11e7-90f8-a0ba96494b7e.png)

**Comment by alex-michel** [comment]
?

**Comment by luwes** [comment]
Hi @alex-michel, it's possible to change this via the `template` option.
See https://github.com/luwes/vimeowrap.js/blob/master/src/plugins/playlist/playlist.js#L30

You'll have to copy that and change the values after truncate.
