### ISSUE TITLE
size of player.js and player.css

### ISSUE THREAD

**Issue by leeoniya** [luwes/vimeowrap.js#26]
hey @luwes 

this isn't specifically about `vimeowrap.js`, but more about embedding Vimeo in general.

my company wants to embed some videos we have on Vimeo in order to affect the view count metrics (not necessarily to save bandwidth).

a quick devtools glance at the help page [1] reveals that `player.js` [2] is 588 KB and `player.css` [3] is 118 KB. this is an order of magnitude more JS and CSS than any of our pages load/SSR (and they're relatively complex e-commence pages). we can probably load this only on demand when a user clicks a thumbnail, but i'm pretty sure this will prevent the necessary autoplay from functioning on mobile, requiring an additional click, making it a no-go UX.

when weighing this against a 0 KB `<video>` alternative, it's a huge pill to swallow simply for the pleasure of registering view counts on Vimeo.

are there any alternative options?

thanks!

[1] https://vimeo.zendesk.com/hc/en-us/articles/224969968-Embedding-videos-overview
[2] https://f.vimeocdn.com/p/3.14.42/js/player.js
[3] https://f.vimeocdn.com/p/3.14.42/css/player.css

**Comment by luwes** [comment]
hey @leeoniya, it is fairly large but it does include a lot of stuff so it plays back on a wide range of devices. It supports Dash, HLS, fallback to progressive, 360 videos/VR, live streaming. Just already having dash playback with ABR can make a big difference to the end user. 

Autoplay can work on mobile but the video would have to be muted initially to be able to load the player on a tap.
https://player.vimeo.com/video/76979871?autoplay=1&muted=1

An other option would be to load the player when it appears in the viewport, lazy loading.

I think between Youtube, Wistia, Vimeo, Facebook, etc. Vimeo still comes up on top in performance and quality but I'm sure there's lighter weight players out there. If your company has a pro account, you could also use the raw video files and manifests in another player like JW player or Shaka player.

https://vimeo.zendesk.com/hc/en-us/articles/224823567-Direct-links-to-video-files

**Comment by leeoniya** [comment]
> it is fairly large but it does include a lot of stuff

makes sense if your core deliverable is a site dedicated to serving media; not so much for once-in-a-while 30s product intros.

> If your company has a pro account, you could also use the raw video files and manifests

we'll try this route first. thanks!
