### ISSUE TITLE
Vimeo playlist issue

### ISSUE THREAD

**Issue by shile23** [luwes/vimeowrap.js#7]
Vimeo plugin is great,it has all i need...but there is a little bug,when i set playlist i wont show the first item imediately because in the src there is no http: before the link,when i click on another playlist item(it works) and when i go back to the first item it also works.I added http: before the link in firebug,but i cant do it in your code.Any help?

**Comment by luwes** [comment]
Seems to work fine here, http://jsfiddle.net/luwes/cWT7k/
